services:
  # workoutapi:
  #   build: ./z-man-workout-api
  #   environment:
  #     - DB_DATASOURCE=${DB_DATASOURCE}
  #     - DB_INITIALCATALOG=${DB_INITIALCATALOG}
  #     - DB_USERID=${DB_USERID}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - JWT_ISSUER=${JWT_ISSUER}
  #     - JWT_AUDIENCE=${JWT_AUDIENCE}
  #     - JWT_SECRETKEY=${JWT_SECRETKEY}
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   networks:
  #     - workoutnetwork
  #   depends_on:
  #     - workoutdb
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - workoutnetwork
    depends_on:
      - workoutdb

  workoutdb:
    image: postgres
    container_name: workoutdb
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: workoutdb
    ports:
      - "5432:5432"
    networks:
      - workoutnetwork
    volumes:
      - WorkoutData:/var/lib/postgresql/data

networks:
  workoutnetwork:
    driver: bridge

volumes:
  WorkoutData:
    driver: local
